markdown: rdiscount
permalink: /posts/:title
rdiscount:
  extensions: [smart]

gems:
  - jekyll-sitemap

name: Nate Collings
url: http://blog.natecollings.com
description: A fantastic blog that is fantastic.
twitter: NateCollings
